#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "OnlyNoahIsAllowedToOpenVersion1.h"

task main()
{
	InitializeTurret();
	NormalOperation();
}
