#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Drive_R,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Drive_L,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     Push,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     Paddle,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     Flag,          tmotorTetrix, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Subrutines.h";

task main()
{
	waitForStart();
	while(true)
	{
  	getJoystickSettings(joystick);

  	if (joy1Btn(6) || joy1Btn(8))
		{
			drive_power = drive_max_power;
		}
		else
		{
			drive_power = drive_min_power;
		}

		initial_power();

  	if (joy1Btn(7) || joy1Btn(5))
		{
			inverse_slave();
		}

		if (joy1Btn(3) || joy2Btn(3))
		{
			nxtDisplayCenteredTextLine (0, "123212321");
			reset();
		}

		if (joy1Btn(1))
		{
			slave();
		}

		if (joy2Btn(5))
		{
			tower_paddle = tower_paddle_power;
		}

		if (joy2Btn(7))
		{
			tower_paddle = tower_paddle_power * -1;
		}

		motor[Drive_R] = Drive_right;
		motor[Drive_L] = Drive_left;
  }
}
