#pragma config(Sensor, S1,     sonar,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "CoordsystemheaderBETA.h"

task main()
{
turnfwd(50,50);


}
