#pragma config(Sensor, S1,     sonic,          sensorSONAR)
#pragma config(Motor,  motorA,          Turret,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Left,          tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ultrasonic.h"

task turret()
{
	while(true)
	{
		nMotorEncoderTarget[Turret] = 0;
		motor[Turret] = -1 * motorMaxPower;
		while(nMotorRunState[Turret] != runStateIdle){}
		motor[Turret] = 0;

		nMotorEncoderTarget[Turret] = 180;
		motor[Turret] = motorMaxPower;
		while(nMotorRunState[Turret] != runStateIdle){}
		motor[Turret] = 0;
	}
}

task drive()
{
	while(true)
	{
		while(forward)
		{
			motor[Left] = motorMaxPower;
			motor[Right] = motorMaxPower;
		}
		motor[Left] = 0;
		motor[Right] = 0;
	}
}

task main()
{
	motorInitialize();
	motorRun();

	StartTask(drive);
	StartTask(turret);
	while(true){}
}
